### ISSUE TITLE
Missing documentation about library dependencies

### ISSUE THREAD

**Issue by twasilczyk** [fdufnews/SMART_Response_BASIC#1]
Starting with a fresh Arduino IDE installation, following build instructions of this project won't help building it. Installing base Arduino board was an easy guess, but then:
- I had to set SD_CARD to 0 (SRXE doesn't have it out of box)
- I had to install MemoryFree library
- despite having SD_CARD set to 0, the build fails on missing references to host_unmountSD
- I guess I installed a wrong MemoryFree library, since the build still fails on calling freeMemory and suggests getFreeMemory

I would suggest trying to build this project with a fresh Arduino IDE installation and documenting all dependencies. I'm happy to verify :)

**Comment by fdufnews** [comment]
The MemoryFree library I use is [this one](https://github.com/McNeight/MemoryFree).
Concerning the conditionnal compilation using SDCard or not, as I always compile with SD_CARD 1 maybe I forget one #if somewhere.
I will update the repo soon.

**Comment by fdufnews** [comment]
Repo updated.
Added a link in README.md to the MemoryFree lib
Now compile with SD_CARD set to 0

**Comment by twasilczyk** [comment]
Thanks! It almost did the trick.

With the new change, the build fails on missing SRXEDecreaseVop. Commenting it out makes the build to finish and the code runs fine on SRXE.

While we're at removing SD card from the build, it would be perfect with SPI memory support as an alternative to SD card. Soldering SPI header is a quick job, adding SD reader not necessarily. But that would be a separate Feature Request, I guess.

**Comment by fdufnews** [comment]
The problem was not in the Basic files but I forget to update the [low level repo](https://github.com/fdufnews/SMART-Response-XE-Low_level).
It's done now

Concerning the SPI memory support it is a choice I made to not implement it as it would have required memory block management, wear leveling and so on. The SPI memory would have been an interresting choice as it would have been possible to use the memory chip that's already in the terminal but the block management was a nightmare requiring large memory buffers. I had neither the time nor the inclination to do it, so I prefered implementing SD card support as all is done either by the sdcard library or inside the card itself.
The sdcard has also the advantage of being read/written on any computer. So files can be backed up on a computer.
The other reason that pushed me the "SDCard way" was the ability to edit files on a computer and copy them to the card.
For the basic files it is currently not possible to do it. I first thinked I could do it redirecting the output of the list statement but I have still not find an elegant way to do it, so I choose to dump program memory to the card. But I am still searching.
I also plan to add support for data files.
